apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fintech
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # si tu clúster tiene otra StorageClass, cámbiala o quítala
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: lilypar59/fintech:db-v1
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: fintech
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
