apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lilypar59/fintech:backend-v1
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fintech
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30082    # NUEVO: puerto externo
  type: NodePort          # ANTES era ClusterIP

