apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: lilypar59/fintech:site-v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: fintech
spec:
  selector:
    app: site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # http://IP_NODE:30080
  type: NodePort
